# Generated by Django 4.0.1 on 2022-02-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comments_options_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Rating'),
        ),
    ]
