# Generated by Django 4.0.1 on 2022-02-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Rating'),
        ),
    ]
